### ISSUE TITLE
Tauri integration

### ISSUE THREAD

**Issue by AndrewJSchoen** [tuzz/game-loop#12]
Hey, So I am interested in possibly using this library within a [Tauri](https://tauri.app)-based application to do some backend computation that is frame-specific. From what I understand, it uses [tao](https://github.com/tauri-apps/tao) (a fork of winit) to do some windowing work. This is more of a question/feature request, but would some sort of tauri integration be something that is planned, or of interest, or better yet, would this already be possible?

**Comment by parasyte** [comment]
If you need to be unblocked in the short term, you can work around this shortcoming by copying this function into your application and changing the `winit` references to `tau`: https://github.com/tuzz/game-loop/blob/1adbcf5b3d3daf0f1e33204039f8f81c986a2c0b/src/helper.rs#L62-L89

In the long-term I expect this to be resolved with an additional abstraction layer. Possibly like the one I described in https://github.com/tuzz/game-loop/pull/10#issuecomment-1197222395

**Comment by tuzz** [comment]
game-loop now supports tao in version 0.10.0. Hopefully that resolves this issue.
