### ISSUE TITLE
Render throttling

### ISSUE THREAD

**Issue by mfluehr** [tuzz/game-loop#24]
I am wondering why `render(g)` is called as often as possible. Wouldn't it be better to cap it? It seems like a waste of processing power to do hundreds/thousands of renders per second.

**Comment by tuzz** [comment]
Good question @mfluehr.

I think, in most cases, your game will either want to render as quickly as possible to get the highest achievable frame rate, or it will be artificially limited by the graphics pipeline. For example, if vsync is enabled, most graphics hardware will limit the number of frames that are queued by synchronously blocking the code when trying to add more frames to the queue.

In many games, there is no frame rate cap and they're allowed to render at a higher frame rate than the monitor, which does seem wasteful, but I think it's up to the implementor how they want to handle this scenario. Arguably, we could add support for capping the render rate in game-loop, but I don't think there's a need. It's fairly easy to add yourself ([see example](https://github.com/tuzz/game-loop/blob/master/examples/game_of_life.rs#L114-L115)).
