### ISSUE TITLE
Make it possible to change updates_per_second while running

### ISSUE THREAD

**Issue by tedsteen** [tuzz/game-loop#3]
When doing rollback networking sometimes a client need to slow down for others to keep up (https://github.com/gschup/ggrs/wiki/5.-Time-Synchronization#manual-time-rift-synchronization)

I couldn't find a way to do this and figured an issue would be a good start to see what you think about it.

**Comment by tuzz** [comment]
I like this idea. I think

**Comment by tuzz** [comment]
(didn't mean to close, apologies)

**Comment by tedsteen** [comment]
If you need any testing I'm in a state where I could test it!

**Comment by tuzz** [comment]
Hello, sorry I haven't had much availability.

I've made an experimental branch ([experimental-set-updates-per-second](https://github.com/tuzz/game-loop/tree/experimental-set-updates-per-second)) that adds a GameLoop::set_updates_per_second method. I haven't written any tests for it but you're welcome to try it and see if it helps your use case. Eventually, I'll write some tests and put this into master.

**Comment by tedsteen** [comment]
> Hello, sorry I haven't had much availability.
> 
> I've made an experimental branch ([experimental-set-updates-per-second](https://github.com/tuzz/game-loop/tree/experimental-set-updates-per-second)) that adds a `GameLoop::set_updates_per_second` method. I haven't written any tests for it but you're welcome to try it and see if it helps your use case. Eventually, I'll write some tests and put this into master.

No worries, I'm just happy to help. Will try out the branch and get back to you.

**Comment by tuzz** [comment]
I've now merged this change into `master` (version 0.9.0 of the crate).

It's still not fully tested at a unit level but hopefully it will do the job. Your mileage may vary.

**Comment by tedsteen** [comment]
Thanks! Sorry for not getting back to you but I never got around to try it out

**Comment by tedsteen** [comment]
I will get there at some point :)

**Comment by tedsteen** [comment]
It works great :)
